### ISSUE TITLE
Can't find composer package

### ISSUE THREAD

**Issue by MathijsDelva** [bobmotor/magento-2-gulp#1]
Hello,

I'm just a beginner but i added "bobmotor/magento-2-gulp":"~1.2.0" to my root composer.json file in Magento2, and after running "composer update --prefer-source", i get the following error:

- - - 
└╼ composer update --prefer-source
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bobmotor/magento-2-gulp could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
- - - 

Am i doing something wrong?

**Comment by spyrule** [comment]
I got this exact same issue.

**Comment by volodymyr-lisniak** [comment]
Sorry, guys, for the late reply.
Now composer is updated and you can try to add these lines to your Magento project `composer.json`

```
"repositories": [
    {
        "type": "github",
        "url": "https://github.com/bobmotor/magento-2-gulp"
    }
],
```
and run `composer require bobmotor/magento-2-gulp`

Also, you can install gulp manually by copying files to the root of your project.

**Comment by volodymyr-lisniak** [comment]
If you will have problems with installation please reopen/open the issue.
