### ISSUE TITLE
Node flags detected: --map

### ISSUE THREAD

**Issue by mattkrupnik** [bobmotor/magento-2-gulp#11]
Hi,

after using --map arg, I got warning ` Node flags detected: --map`. My node version 10.13.0. When I changed arg value from `map` to `maps` everything was fine.

**Comment by volodymyr-lisniak** [comment]
Hi! 
Get the same warning on the `v10.16.3`
Please, run `sudo npm install gulp-cli -g`

Similar issue https://github.com/gulpjs/gulp/issues/1564 with gulp

**Comment by volodymyr-lisniak** [comment]
@mattkrupnik if you have found this problem again, please reopen the issue.
