### ISSUE TITLE
Lost sourcemaps from time to time

### ISSUE THREAD

**Issue by mattkrupnik** [bobmotor/magento-2-gulp#16]
Hi, do you have any problem with sourcemaps? I lost it from time to time. When I manualy refresh page then everything is fine, but when I do any changes in less files then sometimes I lost sourcemap, then instead for example `*\*\_module.less` I get `*\*\styles-m.css?livereload=1585657356640` on BrowserSync this same, browser Chrome latest version.

**Comment by volodymyr-lisniak** [comment]
Hi @mattkrupnik
Sorry for the late reply.
I'll try to test this behavior .

**Comment by mattkrupnik** [comment]
> Hi @mattkrupnik
> Sorry for the late reply.
> I'll try to test this behavior .

OK let me know, thanks!

**Comment by mattkrupnik** [comment]
@bobmotor did you have a chance to look on it?

**Comment by bobmotor** [comment]
@mattkrupnik no, man, I didn't have time to find a solution :(

**Comment by volodymyr-lisniak** [comment]
@mattkrupnik no, man, I didn't have time to find a solution :(

**Comment by volodymyr-lisniak** [comment]
@mattkrupnik I have the same problem with sourcemaps in chrome. 
Updated all project dependencies including BrowserSync and Livereload [1.5.0](https://github.com/bobmotor/magento-2-gulp/releases/tag/v1.5.0) but no luck. I think we have a problem with Chrome though any browser updates that should fix this bug.

**Comment by metalist1492** [comment]
Together with the watch, the gulp does not break, it works clearly. Your build version gulp is 1.5.0
Chrome browser version 101.0.4951.64 (Official Build) (64-bit)
