### ISSUE TITLE
Already have package.json file in the root (default Magento package.json for grunt)

### ISSUE THREAD

**Issue by VivekShingala** [bobmotor/magento-2-gulp#19]
Hi

Thank you for the extension. I am trying it out on my Magento store.

However, I am stuck on the step where I have to copy package.json.sample-aws to package.json because I already have Magento's package.json file for grunt.

How should I handle this?

**Comment by vlisnyak** [comment]
Hi @VivekShingala 

You could simply remove your old `package.json` and rename new one or just copy content from the `package.json.sample-aws` to the your `package.json`.

**Comment by volodymyr-lisniak** [comment]
Hi @VivekShingala 

You could simply remove your old `package.json` and rename new one or just copy content from the `package.json.sample-aws` to the your `package.json`

Also need to remove your `node_modules` directory before run `npm i`
