### ISSUE TITLE
Error: Cannot find module 'strip-ansi'

### ISSUE THREAD

**Issue by VivekShingala** [bobmotor/magento-2-gulp#20]
I am getting this error when trying to run gulp commands.

`gulp clean --clothing && gulp exec --clothing && gulp less --clothing --map --min`

Getting below error.

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'strip-ansi'
```

I tried installing strip-ansi package but still getting the same error.

`npm i strip-ansi`

**Comment by volodymyr-lisniak** [comment]
@VivekShingala 
Could you provide your local environment:
- `OS`
- `nodejs` version
- `gulp` version

**Comment by VivekShingala** [comment]
Hi @bobmotor 

I am trying this on local environment using MAMP on Mac.

```
node -v
v13.11.0
```
```
npm -v
6.14.8
```
`"gulp": "^4.0.2"`

**Comment by volodymyr-lisniak** [comment]
Please downgrade your `Gulp` version to `3.x.x`

**Comment by VivekShingala** [comment]
Hi @bobmotor 

Changing gulp version to 3.x.x lead me to a different error.

```
fs.js:39
} = primordials;
    ^

ReferenceError: primordials is not defined
```
It was fixed by "Using npm-force-resolutions as a preinstall script," as described here.
[How to fix ReferenceError: primordials is not defined in node](https://stackoverflow.com/a/58394828)

After fixing it commands from this extension ran properly.

Thanks a lot.
