### ISSUE TITLE
The following tasks did not complete: critical

### ISSUE THREAD

**Issue by mrtuvn** [bobmotor/magento-2-gulp#22]
Thanks for your great work
I have setup in my local
OS : ubuntu 20.04.1
node: 14.15.3
npm: 6.14.9
Magento use latest current branch

I have updated some dependencies in package.json to more recent version
But when i try run command critical (Production mode in local + all cache enable + run static content deploy)

i got message show 
The following tasks did not complete: critical
Did you forget to signal async completion?
Is this normal ?

When i navigate to pub/static/theme i found critical.css file size seem to high comparing with sample luma theme file (Only ~8KB)

**Comment by mrtuvn** [comment]
Here is content package.json

`"devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.12.1",
    "browser-sync": "^2.26.13",
    "del": "^3.0.0",
    "eslint": "^4.17.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "exec-queue": "0.0.2",
    "gulp": "^4.0.2",
    "gulp-babel": "^8.0.0",
    "gulp-cache": "^1.0.2",
    "gulp-changed": "^3.2.0",
    "gulp-clean": "^0.4.0",
    "gulp-color": "0.0.1",
    "gulp-concat-css": "^3.1.0",
    "gulp-cssmin": "^0.2.0",
    "gulp-expect-file": "^1.0.2",
    "gulp-if": "^3.0.0",
    "gulp-less": "^3.5.0",
    "gulp-sass": "^4.1.0",
    "gulp-livereload": "^3.8.1",
    "gulp-load-plugins": "^1.5.0",
    "gulp-prettier-eslint": "^1.1.0",
    "gulp-rename": "^1.4.0",
    "gulp-replace": "^1.0.0",
    "gulp-sourcemaps": "^2.6.5",
    "gulp-svg-sprite": "^1.5.0",
    "gulp-svgmin": "^1.2.4",
    "lint-staged": "^6.1.0",
    "penthouse": "^2.3.2",
    "plugin-error": "^1.0.1",
    "require-dir": "^0.3.2",
    "run-sequence": "^2.2.1",
    "stylelint": "^11.1.1",
    "stylelint-order": "^0.8.1"
  }`

**Comment by vlisnyak** [comment]
@mrtuvn Can you try to use node v10 (ex. `v10.16.3`)?
I'm going to update repository to support `gulp v4` and `node v14` in the next update.

The size of the `critical.css` can be any, depending on your settings.
`dev/tools/gulp/configs/criticalConfig.js`
```
module.exports = {
    ...
    width: 1920,
    height: 900,
    ...
};
```

**Comment by mrtuvn** [comment]
Thanks you for response. Will try again as your suggestions. I only got notes in command terminal. But file generated success and results make me supprise at file size compare with luma

**Comment by vlisnyak** [comment]
You can try to erase `style-m.css` and `style-m.css` or remove them and see what you get with the only `critical.css`. 
If you get the styled top side of the page (`900px` by default) - you're on the right track.
