### ISSUE TITLE
local-themes.js instead of themes.js

### ISSUE THREAD

**Issue by sprankhub** [bobmotor/magento-2-gulp#3]
First, thanks for the awesome work!

I guess you agree when I say that it is bad practice to touch any core files. Hence, I kindly ask you to switch from the `themes.js` file to the `local-themes.js` file. See e.g.:

https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/tools/using_grunt.html#grunt_config
https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/css-topics/css_debug.html#add_theme

**Comment by volodymyr-lisniak** [comment]
Thanks for your investment. I totally agree with this.
And we already have merged [pull request](https://github.com/bobmotor/magento-2-gulp/pull/4/files)
Please update to the new `v1.3.4` version.
